$("document").ready(function(){
    $(".navtoggler").on("click",function(){
        $(".togglenav").toggle(
            function(){
                $(this).addClass("hide");
            },function(){
                $(this).removeClass("hide");
            }
        )
    });
});
